export default [
    {
        "OrgName": "Kanthaus",
        "ArtID": "KAN001",
        "ArtTitle": "Constitution",
        "ArtLink": "https://kanthaus.online/en/governance/constitution",
        "Lang": "EN",
        "NumChars": 15092,
        "SupBy": "",
    },
    {
        "OrgName": "Kanthaus",
        "ArtID": "KAN001",
        "ArtTitle": "Verfassung",
        "ArtLink": "https://kanthaus.online/de/governance/constitution",
        "Lang": "DE",
        "NumChars": 17327,
        "SupBy": "",
    },
    {
        "OrgName": "Kanthaus",
        "ArtID": "KAN002",
        "ArtTitle": "Collective Agreements",
        "ArtLink": "https://kanthaus.online/en/governance/collectiveagreements",
        "Lang": "EN",
        "NumChars": 4385,
        "SupBy": "KAN001",
    },
    {
        "OrgName": "Kanthaus",
        "ArtID": "KAN002",
        "ArtTitle": "Gemeinschaftliche Vereinbarungen",
        "ArtLink": "https://kanthaus.online/de/governance/collectiveagreements",
        "Lang": "DE",
        "NumChars": 5280,
        "SupBy": "KAN001",
    },
    {
        "OrgName": "S14",
        "ArtID": "S14001",
        "ArtTitle": "(no title)",
        "ArtLink": "https://www.ooooo.be/etherhtml/e2h.php?_=S14",
        "Lang": "EN",
        "NumChars": 20292,
        "SupBy": "",
    },
    {
        "OrgName": "Schwarz 10",
        "ArtID": "SCH001",
        "ArtTitle": "Task Auction",
        "ArtLink": "http://schwarz10.de/taskauction/index.html",
        "Lang": "EN",
        "NumChars": 5393,
        "SupBy": "",
    },
    {
        "OrgName": "Schwarz 10",
        "ArtID": "SCH002",
        "ArtTitle": "Wahlbörse",
        "ArtLink": "http://schwarz10.de/wahlboerse/index.html",
        "Lang": "EN",
        "NumChars": 2732,
        "SupBy": "",
    },
]