export default [
    {
        "organizationName": "Kanthaus",
        "artefactTitle": "Constitution",
        "artefactLink": "https://kanthaus.online/en/governance/constitution",
        "language": "EN",
        "numberOfCharacters": 15092,
    },
    {
        "organizationName": "Kanthaus",
        "artefactTitle": "Verfassung",
        "artefactLink": "https://kanthaus.online/de/governance/constitution",
        "translationOf": "Constitution",
        "translationOfLink": "https://kanthaus.online/en/governance/constitution",
        "language": "DE",
        "numberOfCharacters": 17327,
    },
    {
        "organizationName": "Kanthaus",
        "artefactTitle": "Collective Agreements",
        "artefactLink": "https://kanthaus.online/en/governance/collectiveagreements",
        "language": "EN",
        "numberOfCharacters": 4385,
    },
    {
        "organizationName": "Kanthaus",
        "artefactTitle": "Gemeinschaftliche Vereinbarungen",
        "artefactLink": "https://kanthaus.online/de/governance/collectiveagreements",
        "translationOf": "Collective Agreements",
        "translationOfLink": "https://kanthaus.online/en/governance/collectiveagreements",
        "language": "DE",
        "numberOfCharacters": 5280,
    },
    {
        "organizationName": "S14",
        "artefactTitle": "(no title)",
        "artefactLink": "https://www.ooooo.be/etherhtml/e2h.php?_=S14",
        "language": "EN",
        "numberOfCharacters": 20292,
    },
    {
        "organizationName": "Schwarz 10",
        "artefactTitle": "Task Auction",
        "artefactLink": "http://schwarz10.de/taskauction/index.html",
        "language": "EN",
        "numberOfCharacters": 5393,
    },
    {
        "organizationName": "Schwarz 10",
        "artefactTitle": "Wahlbörse",
        "artefactLink": "http://schwarz10.de/wahlboerse/index.html",
        "language": "EN",
        "numberOfCharacters": 2732,
    },
]